# Generated by Django 4.1.4 on 2023-01-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Credit", "Credit"),
                    ("Full Payment", "Full Payment"),
                    ("Part Payment", "Part Payment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=50, null=True)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "purchased_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "purchased_by",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "purchased_from",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "unit_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sale_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "delivery_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "waybill_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sale_by", models.CharField(blank=True, max_length=50, null=True)),
                ("sale_to", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unit_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Credit", "Credit"),
                            ("Full Payment", "Full Payment"),
                            ("Part Payment", "Part Payment"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reorder_level",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("expiry", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                    ),
                ),
            ],
        ),
    ]
