# Generated by Django 4.1.4 on 2023-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_stock_yet_to_deliver_alter_cash_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="receipt_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Credit", "Credit"),
                    ("Full Payment", "Full Payment"),
                    ("Part Payment", "Part Payment"),
                    ("Take Balance", "Part Payment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Credit", "Credit"),
                    ("Full Payment", "Full Payment"),
                    ("Part Payment", "Part Payment"),
                    ("Take Balance", "Part Payment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
