# Generated by Django 4.1.4 on 2023-01-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_stockhistory_receipt_no_alter_stock_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stockhistory",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
