# Generated by Django 4.1.4 on 2023-01-16 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_stock_balance_stockhistory_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockhistory",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
