# Generated by Django 4.1.4 on 2023-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_stockhistory_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockhistory",
            name="yet_to_deliver",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
